language: python
services:
  - xvfb
addons:
  apt:
    packages:
      - firefox
      - firefox-geckodriver
python:
  - 2.7
install: pip install tox-travis
script:
  - DISPLAY=:99 xvfb-run -n 99 --server-args="-screen 0 1024x768x24" tox -e py27-wsgi-ff-head -- --reruns=0
after_failure:
  - cat geckodriver.log
cache:
  pip: true
  directories:
  - eggs/
