language: python
services:
  - xvfb
addons:
  apt:
    packages:
      - firefox
      - firefox-geckodriver
python:
  - 2.7
  - 3.6
  - 3.7
install: pip install tox-travis
script:
  - tox
cache:
  pip: true
  directories:
  - eggs/
