# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: gocept/pipelines-selenium:latest

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - tox -epy37-wsgi-ff-headless
    - parallel:
      - step:
          name: Py27-FF-head
          script:
            - tox -py27-wsgi-ff-head,py27-plonetesting-ff-head,py27-grok-ff-head
      - step:
          name: Py27-FF-headless
          script:
            - tox -epy27-wsgi-ff-headless,py27-plonetesting-ff-headless,py27-grok-ff-headless
      - step:
          name: Py36-FF-head
          script:
            - tox -py36-wsgi-ff-head,py36-plonetesting-ff-head,py36-grok-ff-head
      - step:
          name: Py36-FF-headless
          script:
            - tox -epy36-wsgi-ff-headless,py36-plonetesting-ff-headless,py36-grok-ff-headless
      - step:
          name: Py37-FF-head
          script:
            - tox -py37-wsgi-ff-head,py37-plonetesting-ff-head,py37-grok-ff-head
      - step:
          name: Py37-FF-headless
          script:
            - tox -epy37-wsgi-ff-headless,py37-plonetesting-ff-headless,py37-grok-ff-headless